package com.example.harleyapp.ui.theme

import androidx.compose.ui.graphics.Color

val HarleyBlue = Color(0xFF3856C8)
val HarleyBlueLight = Color(0xFFDDE4FF)
val HarleyTeal = Color(0xFF006C69)
val HarleyTealLight = Color(0xFF9EF2ED)
val HarleyOrange = Color(0xFF8D4F00)
val HarleyOrangeLight = Color(0xFFFFDCB4)
val HarleyBackground = Color(0xFFF7F8FC)
val HarleySurface = Color(0xFFFFFFFF)
val HarleyText = Color(0xFF191B23)

val HarleyBlueDark = Color(0xFFB8C4FF)
val HarleyTealDark = Color(0xFF81D5D1)
val HarleyOrangeDark = Color(0xFFFFB86B)
val HarleyDarkBackground = Color(0xFF111318)
val HarleyDarkSurface = Color(0xFF1B1D24)

val SakuraPink = Color(0xFFC33C83)
val SakuraPinkLight = Color(0xFFFFD8E9)
val SakuraPurple = Color(0xFF76518A)
val SakuraPurpleLight = Color(0xFFF1D8FF)
val SakuraOrange = Color(0xFFA24200)
val SakuraOrangeLight = Color(0xFFFFDBCA)
val SakuraBackground = Color(0xFFFFF7FA)
val SakuraText = Color(0xFF26171F)
val SakuraPinkDark = Color(0xFFFFADD0)
val SakuraPurpleDark = Color(0xFFDCB8F0)
val SakuraOrangeDark = Color(0xFFFFB691)
val SakuraDarkBackground = Color(0xFF1F1119)
val SakuraDarkSurface = Color(0xFF2A1922)

val StarryIndigo = Color(0xFF4D5BD4)
val StarryIndigoLight = Color(0xFFDFE0FF)
val StarryCyan = Color(0xFF007A82)
val StarryCyanLight = Color(0xFFAAF1FA)
val StarryGold = Color(0xFF875300)
val StarryGoldLight = Color(0xFFFFDEA5)
val StarryBackground = Color(0xFFF8F8FF)
val StarryText = Color(0xFF191A2C)
val StarryIndigoDark = Color(0xFFBCC2FF)
val StarryCyanDark = Color(0xFF79D6DF)
val StarryGoldDark = Color(0xFFFFBA45)
val StarryDarkBackground = Color(0xFF111322)
val StarryDarkSurface = Color(0xFF1B1D31)

val MintGreen = Color(0xFF007C73)
val MintGreenLight = Color(0xFF9EF2E7)
val MintOrange = Color(0xFF8E4E00)
val MintOrangeLight = Color(0xFFFFDCB6)
val MintPurple = Color(0xFF7B4E7B)
val MintPurpleLight = Color(0xFFFFD6FA)
val MintBackground = Color(0xFFF4FCFA)
val MintText = Color(0xFF14201E)
val MintGreenDark = Color(0xFF7DD8CC)
val MintOrangeDark = Color(0xFFFFB86E)
val MintPurpleDark = Color(0xFFE9B7E5)
val MintDarkBackground = Color(0xFF0D1715)
val MintDarkSurface = Color(0xFF17211F)
