package com.example.harleyapp.ui.theme

import androidx.compose.ui.graphics.Color

/*
 * 经典蓝主题。
 *
 * 主色负责主要操作，青绿色负责状态与次级操作，暖橙色只承担提醒和少量数据强调。
 * 每套主题都显式提供容器色与中性色，避免Material默认紫色混入自定义主题。
 */
val HarleyBlue = Color(0xFF3F5ACD)
val HarleyBlueLight = Color(0xFFDDE5FF)
val HarleyBlueContainerText = Color(0xFF10235E)
val HarleyTeal = Color(0xFF0B7773)
val HarleyTealLight = Color(0xFFB8EFEB)
val HarleyTealContainerText = Color(0xFF002F2D)
val HarleyOrange = Color(0xFF9A570B)
val HarleyOrangeLight = Color(0xFFFFE0BD)
val HarleyOrangeContainerText = Color(0xFF321B00)
val HarleyBackground = Color(0xFFF6F7FB)
val HarleySurface = Color(0xFFFFFFFF)
val HarleySurfaceLow = Color(0xFFF1F3F9)
val HarleySurfaceContainer = Color(0xFFEBEEF6)
val HarleySurfaceHigh = Color(0xFFE5E9F2)
val HarleySurfaceHighest = Color(0xFFDDE2EC)
val HarleyText = Color(0xFF191C24)
val HarleyMutedText = Color(0xFF5D6472)
val HarleyOutline = Color(0xFF757C8A)
val HarleyOutlineVariant = Color(0xFFC5CAD5)

val HarleyBlueDark = Color(0xFFB7C4FF)
val HarleyBlueDarkOn = Color(0xFF152866)
val HarleyBlueDarkContainer = Color(0xFF304794)
val HarleyBlueDarkContainerText = Color(0xFFDEE5FF)
val HarleyTealDark = Color(0xFF7BD8D2)
val HarleyTealDarkOn = Color(0xFF003735)
val HarleyTealDarkContainer = Color(0xFF14514F)
val HarleyTealDarkContainerText = Color(0xFFA3F4EF)
val HarleyOrangeDark = Color(0xFFF0B878)
val HarleyOrangeDarkOn = Color(0xFF4A2800)
val HarleyOrangeDarkContainer = Color(0xFF6A3A08)
val HarleyOrangeDarkContainerText = Color(0xFFFFE0BB)
val HarleyDarkBackground = Color(0xFF0D1117)
val HarleyDarkSurface = Color(0xFF141A22)
val HarleyDarkSurfaceLow = Color(0xFF111820)
val HarleyDarkSurfaceContainer = Color(0xFF17202A)
val HarleyDarkSurfaceHigh = Color(0xFF1D2935)
val HarleyDarkSurfaceHighest = Color(0xFF253342)
val HarleyDarkText = Color(0xFFE7ECF4)
val HarleyDarkMutedText = Color(0xFFB7C1CF)
val HarleyDarkOutline = Color(0xFF84909F)
val HarleyDarkOutlineVariant = Color(0xFF3B4654)

/* 樱粉主题：保留柔和气质，同时降低大面积粉紫色的饱和度。 */
val SakuraPink = Color(0xFFAE356E)
val SakuraPinkLight = Color(0xFFFFD9E6)
val SakuraPinkContainerText = Color(0xFF3E0023)
val SakuraPurple = Color(0xFF725182)
val SakuraPurpleLight = Color(0xFFF5D9FF)
val SakuraPurpleContainerText = Color(0xFF2D123B)
val SakuraOrange = Color(0xFF9B4D2C)
val SakuraOrangeLight = Color(0xFFFFDBCE)
val SakuraOrangeContainerText = Color(0xFF3A0B00)
val SakuraBackground = Color(0xFFFFF8FA)
val SakuraSurface = Color(0xFFFFFFFF)
val SakuraSurfaceLow = Color(0xFFFFF0F5)
val SakuraSurfaceContainer = Color(0xFFF9EAEF)
val SakuraSurfaceHigh = Color(0xFFF3E4EA)
val SakuraSurfaceHighest = Color(0xFFEDDEE4)
val SakuraText = Color(0xFF25181E)
val SakuraMutedText = Color(0xFF6C5962)
val SakuraOutline = Color(0xFF88717B)
val SakuraOutlineVariant = Color(0xFFDCC1CB)

val SakuraPinkDark = Color(0xFFFFB0CE)
val SakuraPinkDarkOn = Color(0xFF650035)
val SakuraPinkDarkContainer = Color(0xFF8A1D52)
val SakuraPinkDarkContainerText = Color(0xFFFFD9E6)
val SakuraPurpleDark = Color(0xFFDFB9EE)
val SakuraPurpleDarkOn = Color(0xFF412650)
val SakuraPurpleDarkContainer = Color(0xFF59406A)
val SakuraPurpleDarkContainerText = Color(0xFFF5D9FF)
val SakuraOrangeDark = Color(0xFFFFB59B)
val SakuraOrangeDarkOn = Color(0xFF5C1A00)
val SakuraOrangeDarkContainer = Color(0xFF7C321B)
val SakuraOrangeDarkContainerText = Color(0xFFFFDBCE)
val SakuraDarkBackground = Color(0xFF180F14)
val SakuraDarkSurface = Color(0xFF21171C)
val SakuraDarkSurfaceLow = Color(0xFF1D1318)
val SakuraDarkSurfaceContainer = Color(0xFF271B21)
val SakuraDarkSurfaceHigh = Color(0xFF302329)
val SakuraDarkSurfaceHighest = Color(0xFF3A2B32)
val SakuraDarkText = Color(0xFFF2E6EB)
val SakuraDarkMutedText = Color(0xFFD2BEC7)
val SakuraDarkOutline = Color(0xFFA98E99)
val SakuraDarkOutlineVariant = Color(0xFF55404A)

/* 星海主题：以靛蓝和青色构成冷静、清晰的夜间层次。 */
val StarryIndigo = Color(0xFF4E5CCB)
val StarryIndigoLight = Color(0xFFE0E2FF)
val StarryIndigoContainerText = Color(0xFF091657)
val StarryCyan = Color(0xFF006E75)
val StarryCyanLight = Color(0xFF9CF1F8)
val StarryCyanContainerText = Color(0xFF002023)
val StarryGold = Color(0xFF8A5900)
val StarryGoldLight = Color(0xFFFFDEA5)
val StarryGoldContainerText = Color(0xFF2C1800)
val StarryBackground = Color(0xFFF7F7FF)
val StarrySurface = Color(0xFFFFFFFF)
val StarrySurfaceLow = Color(0xFFF1F1FB)
val StarrySurfaceContainer = Color(0xFFEBEBF5)
val StarrySurfaceHigh = Color(0xFFE5E5EF)
val StarrySurfaceHighest = Color(0xFFDEDFE9)
val StarryText = Color(0xFF1A1B29)
val StarryMutedText = Color(0xFF606172)
val StarryOutline = Color(0xFF777889)
val StarryOutlineVariant = Color(0xFFC7C7D5)

val StarryIndigoDark = Color(0xFFBEC2FF)
val StarryIndigoDarkOn = Color(0xFF17206A)
val StarryIndigoDarkContainer = Color(0xFF354092)
val StarryIndigoDarkContainerText = Color(0xFFE0E2FF)
val StarryCyanDark = Color(0xFF82D5DD)
val StarryCyanDarkOn = Color(0xFF00363B)
val StarryCyanDarkContainer = Color(0xFF004F55)
val StarryCyanDarkContainerText = Color(0xFF9CF1F8)
val StarryGoldDark = Color(0xFFF6BD66)
val StarryGoldDarkOn = Color(0xFF492900)
val StarryGoldDarkContainer = Color(0xFF684000)
val StarryGoldDarkContainerText = Color(0xFFFFDEA5)
val StarryDarkBackground = Color(0xFF0D1020)
val StarryDarkSurface = Color(0xFF141829)
val StarryDarkSurfaceLow = Color(0xFF111526)
val StarryDarkSurfaceContainer = Color(0xFF191E32)
val StarryDarkSurfaceHigh = Color(0xFF20263B)
val StarryDarkSurfaceHighest = Color(0xFF293047)
val StarryDarkText = Color(0xFFE8E8F6)
val StarryDarkMutedText = Color(0xFFC2C3D4)
val StarryDarkOutline = Color(0xFF8D8EA0)
val StarryDarkOutlineVariant = Color(0xFF414456)

/* 薄荷主题：以低饱和深绿为底，人物主题下也保持工具类App的清爽质感。 */
val MintGreen = Color(0xFF006F66)
val MintGreenLight = Color(0xFFA5F2E8)
val MintGreenContainerText = Color(0xFF00201D)
val MintOrange = Color(0xFF88511B)
val MintOrangeLight = Color(0xFFFFDCC2)
val MintOrangeContainerText = Color(0xFF311300)
val MintPurple = Color(0xFF77536F)
val MintPurpleLight = Color(0xFFFFD7F5)
val MintPurpleContainerText = Color(0xFF2E1129)
val MintBackground = Color(0xFFF3FBF8)
val MintSurface = Color(0xFFFFFFFF)
val MintSurfaceLow = Color(0xFFEFF8F5)
val MintSurfaceContainer = Color(0xFFE8F2EF)
val MintSurfaceHigh = Color(0xFFE1ECE8)
val MintSurfaceHighest = Color(0xFFD9E5E1)
val MintText = Color(0xFF14201D)
val MintMutedText = Color(0xFF586963)
val MintOutline = Color(0xFF6F817A)
val MintOutlineVariant = Color(0xFFBECFC9)

val MintGreenDark = Color(0xFF82D8CD)
val MintGreenDarkOn = Color(0xFF003731)
val MintGreenDarkContainer = Color(0xFF07544E)
val MintGreenDarkContainerText = Color(0xFFA5F2E8)
val MintOrangeDark = Color(0xFFFFB87B)
val MintOrangeDarkOn = Color(0xFF4A2806)
val MintOrangeDarkContainer = Color(0xFF663B16)
val MintOrangeDarkContainerText = Color(0xFFFFDCC2)
val MintPurpleDark = Color(0xFFE5B9DB)
val MintPurpleDarkOn = Color(0xFF45263F)
val MintPurpleDarkContainer = Color(0xFF5D3C56)
val MintPurpleDarkContainerText = Color(0xFFFFD7F5)
val MintDarkBackground = Color(0xFF071310)
val MintDarkSurface = Color(0xFF0E1C18)
val MintDarkSurfaceLow = Color(0xFF0A1814)
val MintDarkSurfaceContainer = Color(0xFF11221D)
val MintDarkSurfaceHigh = Color(0xFF182B25)
val MintDarkSurfaceHighest = Color(0xFF20372F)
val MintDarkText = Color(0xFFDDEFEA)
val MintDarkMutedText = Color(0xFFB2CBC3)
val MintDarkOutline = Color(0xFF7E9890)
val MintDarkOutlineVariant = Color(0xFF344B44)

/* 错误色为全部角色主题共享的语义颜色，确保危险操作在换肤后仍有一致含义。 */
val HarleyError = Color(0xFFBA1A1A)
val HarleyOnError = Color(0xFFFFFFFF)
val HarleyErrorContainer = Color(0xFFFFDAD6)
val HarleyOnErrorContainer = Color(0xFF410002)
val HarleyErrorDark = Color(0xFFFFB4AB)
val HarleyOnErrorDark = Color(0xFF690005)
val HarleyErrorContainerDark = Color(0xFF93000A)
val HarleyOnErrorContainerDark = Color(0xFFFFDAD6)
